"""Curated investment themes seed data. Static reference data — pure content layer."""

THEMES = [
    {
        "slug": "artificial-intelligence",
        "name": "Artificial Intelligence",
        "category": "Technology",
        "tagline": "The infrastructure layer of the next industrial revolution",
        "accent_color": "#7C5CFF",
        "hero_image_url": "https://images.unsplash.com/photo-1674027444485-cec3da58eef4?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjY2NzV8MHwxfHNlYXJjaHwxfHxhcnRpZmljaWFsJTIwaW50ZWxsaWdlbmNlJTIwYWJzdHJhY3QlMjBkYXJrfGVufDB8fHx8MTc4MDc3NjA1OXww&ixlib=rb-4.1.0&q=85",
        "micro_thesis": [
            "Generative AI is shifting compute spend from CPU-centric workloads to GPU/accelerator clusters, creating a multi-trillion-dollar infrastructure cycle.",
            "Hyperscalers are committing $200B+ in annual capex toward AI data centers, directly benefiting silicon designers, foundries, and networking suppliers.",
            "Software incumbents with proprietary data moats and distribution can monetize AI as a margin-expansion lever rather than facing disruption.",
        ],
        "key_risks": [
            "Compute supply bottlenecks could compress GPU pricing power as TSMC/Samsung capacity ramps.",
            "Regulatory scrutiny on training data and model safety may slow enterprise adoption.",
            "Energy and cooling constraints limit data-center buildout in tier-1 metros.",
            "Open-source frontier models could commoditize the API layer faster than expected.",
        ],
        "stocks": [
            {"symbol": "NVDA", "name": "NVIDIA Corp"},
            {"symbol": "MSFT", "name": "Microsoft Corp"},
            {"symbol": "GOOGL", "name": "Alphabet Inc"},
            {"symbol": "META", "name": "Meta Platforms"},
            {"symbol": "AMD", "name": "Advanced Micro Devices"},
        ],
    },
    {
        "slug": "electric-vehicles",
        "name": "Electric Vehicles",
        "category": "Mobility",
        "tagline": "Electrification of global transportation",
        "accent_color": "#00D084",
        "hero_image_url": "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        "micro_thesis": [
            "Global EV penetration is projected to exceed 40% of new car sales by 2030, driven by policy mandates and battery cost declines.",
            "Vertical integration in batteries, software, and charging networks separates winners from laggards in a brutally capital-intensive industry.",
            "China dominates the supply chain — Western OEMs that secure lithium, nickel, and rare-earth offtake agreements compound advantages.",
        ],
        "key_risks": [
            "Slowing demand growth in developed markets as early adopters saturate.",
            "Price wars led by Chinese OEMs compress global margins.",
            "Lithium and rare-earth supply concentration creates geopolitical risk.",
            "Charging-infrastructure rollout lags consumer adoption in suburban/rural regions.",
        ],
        "stocks": [
            {"symbol": "TSLA", "name": "Tesla Inc"},
            {"symbol": "RIVN", "name": "Rivian Automotive"},
            {"symbol": "LCID", "name": "Lucid Group"},
            {"symbol": "F", "name": "Ford Motor Co"},
            {"symbol": "GM", "name": "General Motors"},
        ],
    },
    {
        "slug": "clean-energy",
        "name": "Clean Energy",
        "category": "Energy",
        "tagline": "Decarbonization of the global grid",
        "accent_color": "#00D084",
        "hero_image_url": "https://images.unsplash.com/photo-1710438399422-2fca27686bcd?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NTY2Njl8MHwxfHNlYXJjaHwzfHxjbGVhbiUyMGVuZXJneSUyMGFic3RyYWN0JTIwZGFya3xlbnwwfHx8fDE3ODA3NzYwNTl8MA&ixlib=rb-4.1.0&q=85",
        "micro_thesis": [
            "Solar and wind LCOE have fallen below fossil-fuel parity in most major markets, making decarbonization an economic, not just regulatory, story.",
            "Inflation Reduction Act and equivalent EU/Asia subsidies underwrite a decade of capital flow into renewables, storage, and transmission.",
            "Grid-scale storage is the unlock — battery deployments are growing 3x faster than solar capacity additions.",
        ],
        "key_risks": [
            "Interest-rate sensitivity: project IRRs compress sharply when financing costs rise.",
            "Policy reversal risk if conservative governments roll back subsidies.",
            "Grid interconnection queues create multi-year project delays.",
            "Module oversupply from Chinese manufacturers pressures pricing.",
        ],
        "stocks": [
            {"symbol": "ENPH", "name": "Enphase Energy"},
            {"symbol": "FSLR", "name": "First Solar"},
            {"symbol": "NEE", "name": "NextEra Energy"},
            {"symbol": "SEDG", "name": "SolarEdge Tech"},
            {"symbol": "PLUG", "name": "Plug Power"},
        ],
    },
    {
        "slug": "cybersecurity",
        "name": "Cybersecurity",
        "category": "Technology",
        "tagline": "Non-discretionary spend in a threat-rich world",
        "accent_color": "#FF3B30",
        "hero_image_url": "https://images.unsplash.com/photo-1614064548237-096f735f344f?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1ODR8MHwxfHNlYXJjaHw0fHxjeWJlcnNlY3VyaXR5JTIwZGlnaXRhbCUyMGRhcmt8ZW58MHx8fHwxNzgwNzc2MDU5fDA&ixlib=rb-4.1.0&q=85",
        "micro_thesis": [
            "Cybersecurity is the most defensive software vertical — CISO budgets grow regardless of macro environment.",
            "Platform consolidation favors a small number of cloud-native vendors (Crowdstrike, Palo Alto, Zscaler) at the expense of legacy point-solutions.",
            "AI-augmented threats (deepfakes, automated phishing) accelerate the upgrade cycle for endpoint and identity vendors.",
        ],
        "key_risks": [
            "Stretched valuations leave little room for execution missteps.",
            "Platform competition from Microsoft (E5 bundle) erodes standalone-vendor pricing power.",
            "Breach events at top vendors damage trust and trigger customer churn.",
            "AI may eventually automate large parts of the SOC, shrinking seat-based revenue.",
        ],
        "stocks": [
            {"symbol": "CRWD", "name": "CrowdStrike Holdings"},
            {"symbol": "PANW", "name": "Palo Alto Networks"},
            {"symbol": "ZS", "name": "Zscaler Inc"},
            {"symbol": "FTNT", "name": "Fortinet Inc"},
            {"symbol": "S", "name": "SentinelOne"},
        ],
    },
    {
        "slug": "semiconductors",
        "name": "Semiconductors",
        "category": "Technology",
        "tagline": "The strategic commodity of the 21st century",
        "accent_color": "#00B4D8",
        "hero_image_url": "https://images.unsplash.com/photo-1518770660439-4636190af475?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        "micro_thesis": [
            "AI compute demand has structurally shifted semis from a cyclical industry to a secular-growth one for leading-edge nodes.",
            "Geopolitical reshoring (CHIPS Act, EU Chips Act, Japan/Korea subsidies) funds a generational capex cycle in fabs and equipment.",
            "ASML's EUV monopoly and TSMC's process leadership create durable competitive moats at the top of the stack.",
        ],
        "key_risks": [
            "Cyclical demand swings in memory and analog could mask the AI growth story.",
            "China–Taiwan geopolitical risk threatens TSMC concentration.",
            "Export controls on advanced chips/equipment limit addressable market in China.",
            "Capacity overbuild post-AI capex could compress utilization rates by 2027.",
        ],
        "stocks": [
            {"symbol": "NVDA", "name": "NVIDIA Corp"},
            {"symbol": "TSM", "name": "Taiwan Semiconductor"},
            {"symbol": "ASML", "name": "ASML Holding"},
            {"symbol": "AMD", "name": "Advanced Micro Devices"},
            {"symbol": "AVGO", "name": "Broadcom Inc"},
        ],
    },
    {
        "slug": "cloud-computing",
        "name": "Cloud Computing",
        "category": "Technology",
        "tagline": "The operating system of modern enterprises",
        "accent_color": "#007AFF",
        "hero_image_url": "https://images.unsplash.com/photo-1451187580459-43490279c0fa?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        "micro_thesis": [
            "Only ~30% of enterprise workloads have migrated to public cloud — a decade-plus growth runway remains.",
            "Hyperscalers (AWS, Azure, GCP) are now the dominant distribution layer for AI, software, and data services.",
            "Margin expansion from custom silicon (Graviton, Trainium, TPU) offsets pricing pressure on commoditized compute.",
        ],
        "key_risks": [
            "Cloud-spend optimization (FinOps) is structurally compressing growth at the top accounts.",
            "Repatriation of certain workloads to on-prem/colo as cloud costs surprise CFOs.",
            "Antitrust scrutiny on hyperscaler bundling practices.",
            "AI capex intensity could pressure free-cash-flow margins for several years.",
        ],
        "stocks": [
            {"symbol": "MSFT", "name": "Microsoft Corp"},
            {"symbol": "AMZN", "name": "Amazon.com Inc"},
            {"symbol": "GOOGL", "name": "Alphabet Inc"},
            {"symbol": "ORCL", "name": "Oracle Corp"},
            {"symbol": "SNOW", "name": "Snowflake Inc"},
        ],
    },
    {
        "slug": "fintech",
        "name": "Fintech",
        "category": "Finance",
        "tagline": "Software is eating financial services",
        "accent_color": "#00D084",
        "hero_image_url": "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        "micro_thesis": [
            "Card networks (Visa, Mastercard) remain the most durable rails — global cash-to-card conversion still has 15+ years to run.",
            "Embedded finance and B2B payments are the next leg of growth, with Stripe-like platforms taking share from legacy processors.",
            "Crypto/stablecoin rails are becoming serious cross-border payment infrastructure — not just speculation vehicles.",
        ],
        "key_risks": [
            "Interchange fee regulation in the US and EU compresses unit economics.",
            "Big Tech (Apple, Google) launching wallet/BNPL products competes directly for the consumer surface.",
            "Credit-cycle deterioration hits lending fintechs hardest.",
            "Stablecoin/CBDC adoption could disintermediate card networks long-term.",
        ],
        "stocks": [
            {"symbol": "V", "name": "Visa Inc"},
            {"symbol": "MA", "name": "Mastercard Inc"},
            {"symbol": "PYPL", "name": "PayPal Holdings"},
            {"symbol": "SQ", "name": "Block Inc"},
            {"symbol": "COIN", "name": "Coinbase Global"},
        ],
    },
    {
        "slug": "biotechnology",
        "name": "Biotechnology",
        "category": "Healthcare",
        "tagline": "GLP-1s, gene editing, and the AI-drug-discovery revolution",
        "accent_color": "#FF6B6B",
        "hero_image_url": "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        "micro_thesis": [
            "GLP-1 agonists (Ozempic, Mounjaro) are a generational drug class with applications expanding well beyond diabetes/obesity.",
            "CRISPR and base-editing therapies have moved from concept to FDA-approved treatments, unlocking entire disease categories.",
            "AI is shrinking drug-discovery timelines from years to months for early-stage screening and protein-folding tasks.",
        ],
        "key_risks": [
            "Drug-pricing reform (IRA negotiation, MFN clauses) caps long-term revenue ceilings.",
            "Clinical-trial failures wipe out single-asset biotechs without warning.",
            "Patent cliffs on flagship drugs create revenue air pockets.",
            "GLP-1 supply constraints and competing molecules compress incumbent share.",
        ],
        "stocks": [
            {"symbol": "LLY", "name": "Eli Lilly & Co"},
            {"symbol": "NVO", "name": "Novo Nordisk"},
            {"symbol": "VRTX", "name": "Vertex Pharmaceuticals"},
            {"symbol": "REGN", "name": "Regeneron Pharma"},
            {"symbol": "CRSP", "name": "CRISPR Therapeutics"},
        ],
    },
    {
        "slug": "space-economy",
        "name": "Space Economy",
        "category": "Industrials",
        "tagline": "The new orbital infrastructure stack",
        "accent_color": "#7C5CFF",
        "hero_image_url": "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        "micro_thesis": [
            "Reusable launch (SpaceX, Rocket Lab) has cut $/kg to orbit by ~10x, opening previously uneconomic markets.",
            "LEO broadband (Starlink, Kuiper) is becoming a real-world ISP category with hundreds of millions of TAM endpoints.",
            "Defense and Earth-observation contracts provide durable revenue floors as commercial demand scales.",
        ],
        "key_risks": [
            "Pure-play space SPACs continue to burn cash with unclear paths to profitability.",
            "Orbital congestion and Kessler-syndrome scenarios threaten the entire LEO economy.",
            "Government contract dependency creates lumpy revenue and budget-cycle risk.",
            "SpaceX's vertical scale could make most public competitors structurally uneconomic.",
        ],
        "stocks": [
            {"symbol": "RKLB", "name": "Rocket Lab USA"},
            {"symbol": "LMT", "name": "Lockheed Martin"},
            {"symbol": "NOC", "name": "Northrop Grumman"},
            {"symbol": "IRDM", "name": "Iridium Communications"},
            {"symbol": "PL", "name": "Planet Labs"},
        ],
    },
    {
        "slug": "ecommerce",
        "name": "E-commerce",
        "category": "Consumer",
        "tagline": "The long tail of digital retail",
        "accent_color": "#FF9F0A",
        "hero_image_url": "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        "micro_thesis": [
            "E-commerce penetration in the US is still only ~16% of retail — Asia and LatAm have higher ceilings.",
            "Logistics infrastructure (last-mile, fulfillment) is the moat — Amazon, MELI, and JD have widened gaps vs. pure-play merchants.",
            "Social commerce and live-shopping (TikTok Shop, Shopee) are reshaping the discovery funnel, especially in emerging markets.",
        ],
        "key_risks": [
            "Tariff and de-minimis policy changes could disrupt Temu/Shein-style cross-border models.",
            "Margin compression from logistics inflation in tight labor markets.",
            "Return-rate trends and ad-spend efficiency are deteriorating for many DTC brands.",
            "Saturation in mature markets caps growth without category expansion.",
        ],
        "stocks": [
            {"symbol": "AMZN", "name": "Amazon.com Inc"},
            {"symbol": "MELI", "name": "MercadoLibre"},
            {"symbol": "SHOP", "name": "Shopify Inc"},
            {"symbol": "SE", "name": "Sea Limited"},
            {"symbol": "PDD", "name": "PDD Holdings"},
        ],
    },
]


def get_categories():
    cats = sorted({t["category"] for t in THEMES})
    return ["All"] + cats


def get_theme_summary(t: dict) -> dict:
    return {
        "slug": t["slug"],
        "name": t["name"],
        "category": t["category"],
        "tagline": t["tagline"],
        "accent_color": t["accent_color"],
        "hero_image_url": t["hero_image_url"],
        "stock_count": len(t["stocks"]),
    }
